language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"


# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests

service:
  - docker
  
install:
  - docke-compose build
  - docker run -d -p 8050:5050
  
script:
  - docker ps | grep -q kiwibot-kda
