version: '3'

services:

  dash:
    image: "${IMAGE_NAME}:${TAG}"
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kiwibotdash
    command: python index.py
    volumes:
      - .:/code
    ports:
      - "80:8050"